# Generated by Django 5.2 on 2025-05-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='company',
            name='members',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
