# Generated by Django 5.2 on 2025-04-17 09:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type de mouvement')),
                ('is_incoming', models.BooleanField(default=True, verbose_name='Est une entrée')),
            ],
            options={
                'verbose_name': 'Type de mouvement',
                'verbose_name_plural': 'Types de mouvement',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du lieu')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('is_warehouse', models.BooleanField(default=False, verbose_name='Est un entrepôt')),
                ('is_store', models.BooleanField(default=False, verbose_name='Est une boutique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='stock.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Code SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('minimum_stock', models.IntegerField(default=10, verbose_name='Stock minimum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de référence')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Effectué par')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.location', verbose_name='Lieu')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.movementtype', verbose_name='Type de mouvement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité actuelle')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité minimum')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('acknowledged', 'Reconnu'), ('resolved', 'Résolu')], default='pending', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.location', verbose_name='Lieu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Alerte de stock',
                'verbose_name_plural': 'Alertes de stock',
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité initiale')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité actuelle')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='stock.location', verbose_name='Lieu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='stock.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Niveau de stock',
                'verbose_name_plural': 'Niveaux de stock',
                'unique_together': {('product', 'location')},
            },
        ),
    ]
