# Generated by Django 5.2 on 2025-05-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('liter', 'Litre'), ('weight', 'Poids'), ('piece', 'Pièce')], default='piece', max_length=50, verbose_name='Unit'),
        ),
    ]
