# Generated by Django 5.2 on 2025-05-03 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='12 rue de la Paix', max_length=150, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Paris', max_length=150, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_store',
            field=models.BooleanField(default=False, verbose_name='Is store'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_warehouse',
            field=models.BooleanField(default=False, verbose_name='Is warehouse'),
        ),
        migrations.AddField(
            model_name='company',
            name='zipcode',
            field=models.CharField(default='75001', max_length=15, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(related_name='company_members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
