# Generated by Django 5.2 on 2025-05-04 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_unit'),
        ('order', '0002_company_address_company_city_company_is_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_state', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Finished', 'Finished')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=150, verbose_name='Référence')),
                ('vat', models.CharField(choices=[('5.5', 'Réduit 5.5%'), ('10', 'Intermédiaire 10%'), ('20', 'Normal 20%')], default='20', max_length=20)),
                ('ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toutes taxes comprises')),
                ('ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hors Taxe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('from_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_from', to='order.company')),
                ('to_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_to', to='order.company')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_order', to='order.stateorder')),
            ],
        ),
        migrations.CreateModel(
            name='LineOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.order')),
            ],
        ),
    ]
