# Generated by Django 5.2 on 2025-05-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_stateorder_order_lineorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateorder',
            name='name',
            field=models.CharField(default='Open', max_length=150, verbose_name='Nom'),
        ),
    ]
