# Generated by Django 5.2 on 2025-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_stateorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ht',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Hors Taxe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ttc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Toutes taxes comprises'),
        ),
    ]
